### ISSUE TITLE
minimal example?

### ISSUE THREAD

**Issue by mr-robot-bb** [gan3sh500/kervolution-pytorch#3]
Not actual an issue but...

A mimimal code example of the layer working correctly would be awesome. [An attempt of this](https://github.com/mr-robot-bb/kervolution/blob/master/Kervolution-AGAIN.ipynb)

**Comment by gan3sh500** [comment]
I'll try to add something like your notebook but first I need to see why its not learning in yours. I'll take a look at it tomorrow.

**Comment by mselimata** [comment]
Your code works @gan3sh500 Here is my mnist example, I hope you merge to help for demonstration. https://github.com/meltemiatay/kervolution-pytorch/blob/master/kervolutionMnist.ipynb

**Comment by gan3sh500** [comment]
Thank you for the example. It's merged now. 🙂
